basePath: /
host: localhost:8000
info:
  contact: {}
  description: API для управления песнями, включая добавление, обновление, удаление
    и получение списка песен.
  title: Songs API
  version: "1.0"
paths: {}
swagger: "2.0"
